FROM golang:1.12-alpine as builder

WORKDIR /go/src/app

COPY ./app.go .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .

FROM alpine:3.10

WORKDIR /app

COPY --from=builder /go/src/app .

ENTRYPOINT ["./app"]